<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tblPreisliste" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tblPreisliste">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="KundenNr" index-key="Kundenkürzel " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="Kundenkürzel Material " primary="yes" unique="yes" clustered="no" order="asc asc"/>
<od:index index-name="tblPreislisteMaterial" index-key="Material " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAC29IjTqhXWEZ5GAFC/OAejAAAAAJvtqN3u1uJAAAAAAAAAAAB0AGIA
bABQAHIAZQBpAHMAbABpAHMAdABlAAAAAAAAAEzB3vlYttURnkYAUL84B6MAAAAA
BC37SfA04kAAAAAAAAAAAHQAYgBsAEYAaQByAG0AZQBuAGwAaQBzAHQAZQAAAAAA
AAD89IjTqhXWEZ5GAFC/OAejBwAAALb0iNOqFdYRnkYAUL84B6NLAHUAbgBkAGUA
bgBrAPwAcgB6AGUAbAAAAAAAAABmwd75WLbVEZ5GAFC/OAejAAAAAG8GCEW21eJA
AAAAAAAAAAB0AGIAbABNAGEAdABlAHIAaQBhAGwAYQByAHQAZQBuAAAAAAAAALn0
iNOqFdYRnkYAUL84B6MHAAAAtvSI06oV1hGeRgBQvzgHo00AYQB0AGUAcgBpAGEA
bAAAAAAAAAC69IjTqhXWEZ5GAFC/OAejBwAAALb0iNOqFdYRnkYAUL84B6NOAGUA
dAB0AG8AcAByAGUAaQBzAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="GUID" type="9" value="Rqj5Q0kMW0WygyZHyOnj+Q==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Kundenkürzel" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3300"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="tblFirmenliste"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ListRows" type="3" value="8"/>
<od:fieldProperty name="ListWidth" type="10" value="0Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Material" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="4785"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="tblMaterialarten"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ListRows" type="3" value="8"/>
<od:fieldProperty name="ListWidth" type="10" value="0Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Nettopreis" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1935"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="#,##0.00 €;-#,##0.00 €"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="Caption" type="12" value="Nettopreis pro t"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>
