<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tblWiegezettel" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tblWiegezettel">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Lfd-Nr" index-key="Lfd-Nr " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABLT/3ePBbWEZ5GAFC/OAejAAAAAGQglG3v1uJAAAAAAAAAAAB0AGIA
bABXAGkAZQBnAGUAegBlAHQAdABlAGwAAAAAAAAATE/93jwW1hGeRgBQvzgHowcA
AABLT/3ePBbWEZ5GAFC/OAejTABmAGQALQBOAHIAAAAAAAAATMHe+Vi21RGeRgBQ
vzgHowAAAABh4w7L79biQAAAAAAAAAAAdABiAGwARgBpAHIAbQBlAG4AbABpAHMA
dABlAAAAAAAAAE1P/d48FtYRnkYAUL84B6MHAAAAS0/93jwW1hGeRgBQvzgHo0sA
dQBuAGQAZQBuAGsA/AByAHoAZQBsAAAAAAAAAE5P/d48FtYRnkYAUL84B6MHAAAA
S0/93jwW1hGeRgBQvzgHo0QAYQB0AHUAbQAAAAAAAAD0Uf3ePBbWEZ5GAFC/OAej
BwAAAEtP/d48FtYRnkYAUL84B6NHAGUAdwBpAGMAaAB0AAAAAAAAAGbB3vlYttUR
nkYAUL84B6MAAAAAbwYIRbbV4kAAAAAAAAAAAHQAYgBsAE0AYQB0AGUAcgBpAGEA
bABhAHIAdABlAG4AAAAAAAAASlH93jwW1hGeRgBQvzgHowcAAABLT/3ePBbWEZ5G
AFC/OAejTQBhAHQAZQByAGkAYQBsAAAAAAAAAHtN9ojsvtURvaAIADagIwMAAAAA
us1VGPA04kAAAAAAAAAAAHQAYgBsAEEAbgBsAGkAZQBmAGUAcgB1AG4AZwBPAHIA
dAAAAAAAAADKT/3ePBbWEZ5GAFC/OAejBwAAAEtP/d48FtYRnkYAUL84B6NBAG4A
bABpAGUAZgBlAHIAdQBuAGcATwByAHQAAAAAAAAAXNYfdyy61RG9oAgANqAjAwAA
AAC7XoZfEJHiQAAAAAAAAAAAdABiAGwAQQBuAGwAaQBlAGYAZQByAGUAcgAAAAAA
AABLUf3ePBbWEZ5GAFC/OAejBwAAAEtP/d48FtYRnkYAUL84B6NBAG4AbABpAGUA
ZgBlAHIAZQByAAAA
"/>
<od:tableProperty name="RowHeight" type="3" value="285"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="1"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="GUID" type="9" value="m1MO9xqq9U+hir4wJkPrHg==
"/>
<od:tableProperty name="OrderBy" type="12" value="[tblWiegezettel].[Lfd-Nr], [tblWiegezettel].[Datum]"/>
<od:tableProperty name="Filter" type="12" value="((([tblWiegezettel].[Kundenkürzel]=&quot;Helmut Haug GmbH&quot;))) AND ([tblWiegezettel].[Material]=&quot;Grünabfall, Feinmaterial (AS 20 02 01)&quot;)"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Lfd-Nr" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="0"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Kundenkürzel" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2145"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="tblFirmenliste"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ListRows" type="3" value="8"/>
<od:fieldProperty name="ListWidth" type="10" value="0Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Datum" minOccurs="1" od:jetType="datetime" od:sqlSType="datetime" od:nonNullable="yes" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Short Date"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Gewicht" minOccurs="1" od:jetType="double" od:sqlSType="float" od:nonNullable="yes" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="2"/>
<od:fieldProperty name="Caption" type="12" value="Gewicht in t"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Material" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2985"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="tblMaterialarten"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ListRows" type="3" value="3"/>
<od:fieldProperty name="ListWidth" type="10" value="0Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="AnlieferungOrt" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2670"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="Caption" type="12" value="Ort der Materialübergabe"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="tblAnlieferungOrt"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ListRows" type="3" value="8"/>
<od:fieldProperty name="ListWidth" type="10" value="0Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="1"/>
<od:fieldProperty name="DefaultValue" type="12" value="&quot;Biebesheim&quot;"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Anlieferer" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2490"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="111"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="tblAnlieferer"/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="ListRows" type="3" value="5"/>
<od:fieldProperty name="ListWidth" type="10" value="0Twip"/>
<od:fieldProperty name="LimitToList" type="1" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="DefaultValue" type="12" value="&quot;Kunde&quot;"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Referenz" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2400"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>
